// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxlnoxgtlczzitxemnuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4bG5veGd0bGN6eml0eGVtbnVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjI3OTcsImV4cCI6MjA2NTgzODc5N30.o3i75O0ficn89aEf8mfBx3YLRk0tQJBTZvWhLqeb3vw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);